add_subdirectory(Sources/SparrowAddressBar)
add_subdirectory(Sources/SparrowBrowser)
add_subdirectory(Sources/SparrowCommands)
add_subdirectory(Sources/SparrowContent)
add_subdirectory(Sources/SparrowContentToolbar)
add_subdirectory(Sources/SparrowDesignSystem)
add_subdirectory(Sources/SparrowHome)
add_subdirectory(Sources/SparrowNetwork)
add_subdirectory(Sources/SparrowProfiles)
add_subdirectory(Sources/SparrowProfileModel)
add_subdirectory(Sources/SparrowSettings)
add_subdirectory(Sources/SparrowSettingsUI)
add_subdirectory(Sources/SparrowSpaces)
add_subdirectory(Sources/SparrowSpacesUI)
add_subdirectory(Sources/SparrowStorage)
add_subdirectory(Sources/SparrowStorageBase)
add_subdirectory(Sources/SparrowSuggest)
add_subdirectory(Sources/SparrowTabs)
add_subdirectory(Sources/SparrowTabsUI)
add_subdirectory(Sources/SparrowToolbelt)
add_subdirectory(Sources/SparrowWeb)
add_subdirectory(Sources/SparrowWindow)
add_subdirectory(Sources/SparrowWindowManager)
add_subdirectory(Sources/SparrowWindowModel)

if(BUILD_TESTING)
add_subdirectory(Tests)
endif()
